// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOcFiekxsMDQTtaCCiMp8RLu-RQF3Z7Z0',
    appId: '1:987279641830:web:b5d4ca98b0bcdb472bff27',
    messagingSenderId: '987279641830',
    projectId: 'expatinfo-auth',
    authDomain: 'expatinfo-auth.firebaseapp.com',
    storageBucket: 'expatinfo-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA48M3fj4rx583BN6zoHZtScjD-g2Qr-RQ',
    appId: '1:987279641830:android:649e4218f4be938b2bff27',
    messagingSenderId: '987279641830',
    projectId: 'expatinfo-auth',
    storageBucket: 'expatinfo-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeCvIGwZUMRHurJbPpvJtjFpLw7nqbBc4',
    appId: '1:987279641830:ios:bda70540c79338512bff27',
    messagingSenderId: '987279641830',
    projectId: 'expatinfo-auth',
    storageBucket: 'expatinfo-auth.appspot.com',
    iosClientId: '987279641830-hkep3mgv4tjtuv5uvofvpskf4suqglmk.apps.googleusercontent.com',
    iosBundleId: 'com.example.expatInfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeCvIGwZUMRHurJbPpvJtjFpLw7nqbBc4',
    appId: '1:987279641830:ios:1f958f51ada31ac02bff27',
    messagingSenderId: '987279641830',
    projectId: 'expatinfo-auth',
    storageBucket: 'expatinfo-auth.appspot.com',
    iosClientId: '987279641830-fa7kv38s8ge7c5h7tbe565toupre4a42.apps.googleusercontent.com',
    iosBundleId: 'com.example.expatInfo.RunnerTests',
  );
}
